name: freebox
description: An app build using Flutter where the user can upload and search Freebox locations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 < 2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.2+1
  firebase_core: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flappy_translator:
    git:
      url: https://github.com/smartnsoft/FlappyTranslator

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flappy_translator:
  input_file_path: "assets_dev/localizations/localizations.csv"
  output_dir: "lib"
  file_name: "localizations"
  class_name: "AppLocalizations"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false
